// kz_memphisblock.res - created with RESGen v2.0.2.
// RES file edited/corrected by spr1n

// .res entries:
maps/surf_memphisblock.res
maps/surf_memphisblock.txt
maps/surf_memphisblock_detail.txt
gfx/bump/spr1n/135_1.tga
gfx/bump/spr1n/Border03_64.tga
gfx/bump/spr1n/Border08_32.tga
gfx/bump/spr1n/Border10_32.tga
gfx/bump/spr1n/BrickWall01_64.tga
gfx/bump/spr1n/col_CE2X001_.tga
gfx/bump/spr1n/e1S_brk13b.tga
gfx/bump/spr1n/e1S_tile02b.tga
gfx/bump/spr1n/e9S_block02bF.tga
gfx/bump/spr1n/oldbrk_01.tga
gfx/bump/spr1n/pk_wall1.tga
gfx/bump/spr1n/sp_egpblocks.tga
gfx/bump/spr1n/sp_egpflr2.tga
gfx/bump/spr1n/sp_egpwall1_.tga
gfx/bump/spr1n/sp_egpwall2_.tga
gfx/bump/spr1n/sp_pyrbrk_5.tga
gfx/bump/spr1n/sp_rock666_f_e5.tga
gfx/bump/spr1n/sp_rope05a.tga
gfx/bump/spr1n/sp_sndripl.tga
gfx/detail/dt_ground1.tga
gfx/detail/dt_ground2.tga
gfx/detail/dt_ground3.tga
gfx/detail/dt_ground4.tga
gfx/detail/dt_metal1.tga
gfx/detail/dt_metal2.tga
gfx/detail/dt_plaster1.tga
gfx/detail/dt_plaster2.tga
gfx/detail/dt_rough1.tga
gfx/detail/dt_smooth1.tga
gfx/detail/dt_stone1.tga
gfx/detail/dt_stone2.tga
gfx/detail/dt_stone3.tga
gfx/detail/dt_stone4.tga
gfx/detail/dt_wood1.tga
gfx/detail/dt_wood2.tga
gfx/detail/tiles.tga
gfx/detail/tilessm.tga
gfx/detail/wood.tga
gfx/env/desert02bk.tga
gfx/env/desert02dn.tga
gfx/env/desert02ft.tga
gfx/env/desert02lf.tga
gfx/env/desert02rt.tga
gfx/env/desert02up.tga
models/memphisblock/egypt_dog1.mdl
models/memphisblock/egypt_nef.mdl
models/memphisblock/fountain2.mdl
models/memphisblock/ladder.mdl
models/memphisblock/sp_torch1.mdl
models/memphisblock/zyn_farao.mdl
models/memphisblock/zyn_stilas.mdl
models/palmtree.mdl
models/spr1n/torch.mdl
sound/spr1n/anubis.wav
sound/spr1n/coolwind2.wav
sound/spr1n/flame.wav
sound/spr1n/idioteque.wav
sound/spr1n/splash.wav
sound/spr1n/tombsound.wav
sound/spr1n/waterfall.wav
sound/spr1n/wind_tunn.wav
sound/waterrun.wav
sprites/glow01.spr
sprites/laserbeam.spr
sprites/spr1n/flame.spr
sprites/spr1n/flare.spr
sprites/spr1n/mapbyspr1n.spr
sprites/spr1n/wsplash3.spr
sprites/xsmoke1.spr
